<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

namespace Micro\Common\Protobuf\Service\GPBMetadata;

class Message
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a91010a0d6d6573736167652e70726f746f121d6d6963726f2e636f6d6d" .
            "6f6e2e70726f746f6275662e7365727669636522240a0752657175657374" .
            "120a0a026964180120012809120d0a05706172616d18022001280922330a" .
            "08526573706f6e7365120c0a04636f6465180120012809120b0a036d7367" .
            "180220012809120c0a0464617461180320012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

