<?php
/**
 * Created by PhpStorm.
 * User: qu
 * Date: 2019/10/31
 * Time: 14:03
 */

namespace Micro\User\Service;


use Illuminate\Support\Facades\Log;
use Micro\Common\Base\BaseService;
use Micro\User\Repo\CommUserInfoRepo;

class MineService extends BaseService
{
    public function getRules()
    {
        parent::getRules(); // TODO: Change the autogenerated stub
    }

    protected $user;

    public function __construct(CommUserInfoRepo $user)
    {
        $this->user = $user;
    }

    //获取的我的信息
    public function getMineInfo($request)
    {
        $userInfo = $this->user->getMineInfo($request['user_id']);
        if(empty($userInfo)){
            Log::info('用户信息获取失败: '.$request['user_id']);
            Err('用户信息获取失败:1010');
        }
        $code = config('const_user.OFFICIALLY.code');
        if(empty($userInfo['gender'])){
            $userInfo['gender']='0090';
        }
        $userInfo['flag'] = 'false';
        $userInfo['level_name'] = config('const_user.'.$userInfo['user_tariff_code'].'.msg');
        if($userInfo['status'] == $code){
            $userInfo['credit_img'] = config('const_bank.'. strtoupper($userInfo['bank_code']).'.code');

            $suffix = substr($userInfo['account_no'],-4,4);

            $userInfo['after'] = $suffix;
            $userInfo['flag'] = 'true';
        }

        $userInfo['mobile'] = Mobile($userInfo['login_name']);
        $userInfo['phone_number'] = $userInfo['login_name'];
        $userInfo['login_name'] = Mobile($userInfo['login_name']);
        $userInfo['level_img'] = config('const_user.'.$userInfo['user_tariff_code'].'.code');
        return $userInfo;
    }

    //查询用户资产    余额
    public function getBalance($request)
    {
        $ret= app('micro-client')
            ->service('Micro\Finance\Service\BalanceInfoService')
            ->micro('aaa')
            ->with('acct_id',1)
            ->with('user_id',$request['user_id'])
            ->run('getAllBalance');
        $ret=$ret['data'];
        array_multisort(array_column($ret,'account_type'),SORT_ASC,$ret);

//        $allBalance = 0.00;
        $list['balance'] = '0.00';
        foreach($ret as $key => $val){
//            $allBalance += $val['balance'];
            $ret[$key]['icon'] = projectConfig('common.assets_icon.'.$val['account_type'].'.icon');
            if($val['account_type'] == projectConfig('const_account.ACCOUNT_TYPE_ASSET.code')) $list['balance'] = $val['balance'];
            if($val['account_type'] == projectConfig('const_account.ACCOUNT_TYPE_POINTS.code')) $list['reward'] = $val['balance'];
        }

        $list['list'] = $ret;
        $list['allBalance']= app('micro-client')
            ->service('Micro\Finance\Service\BalanceInfoService')
            ->micro('aaa')
            ->with('user_id',$request['user_id'])
            ->run('getAllProfit');
        foreach ($list['list'] as $value){
            if($value['account_type']=='10'){
                $ret=$value;
            }
        }
        return $ret;
    }

    //获取用户手机号
    public function getUserMobile($request){
        return $this->user->getUserMobile($request['user_id']);
    }
}