<?php
/**
 * Created by PhpStorm.
 * User: qu
 * Date: 2019/11/28
 * Time: 10:12
 */

namespace Micro\User\Service;


use Illuminate\Support\Facades\Log;
use Micro\Common\Base\BaseService;
use Micro\User\Repo\CommBankDbRepo;
use Micro\User\Repo\CommSupportBankInfoRepo;
use Micro\User\Repo\SysCityRepo;

class SystemService extends BaseService
{
    public function getRules()
    {
        parent::getRules(); // TODO: Change the autogenerated stub
    }

    //根据城市,银行  获取银联列表
    public function getAreaBankList(CommBankDbRepo $repo,$request)
    {
        //添加 / 更新
//        Redis::zadd('113082355707344578',10,'1130823557073447123');
        // 普通查询
//        Redis::zrange('user_id',0,10,'WITHSCORES');
        // 根据分数从高到底 排序
//        Redis::ZREVRANGE('user_id',0,10,'WITHSCORES');
        return $repo->getAreaBankList($request);
    }

    //获取银行接口
    public function getSupportBankList(CommSupportBankInfoRepo $repo)
    {
        Log::info('获取银行列表');
        return $repo->getSupportBankList();
    }

    //查询省
    public function getProvinceList(SysCityRepo $repo)
    {
        return $repo->getProvinceList();
    }

    //查询市
    public function getCityList(SysCityRepo $repo,$request)
    {
        return $repo->getCityListByProvinceId($request['provinceId']);
    }
}