<?php
/**
 * Created by PhpStorm.
 * User: qu
 * Date: 2019/11/22
 * Time: 9:29
 */

namespace Micro\User\Service;


use Micro\Common\Base\BaseService;
use SimpleSoftwareIO\QrCode\Facades\QrCode;

class UserService extends BaseService
{
    public function getRules()
    {
        parent::getRules(); // TODO: Change the autogenerated stub
    }
    //生成二维码
    public function generateCode($request)
    {
        $url = projectConfig('common.general_code').$request['userId'];
//        $dir = 'Data/upload/qrcode/'.'/qccode_'.rand(1000,9999).'.png';
        $dir = 'Data/upload/qrcode/'.'qr'.$request['userId'].'.png';
        QrCode::format('png')->size('200')->margin(0)->generate($url,$dir); //保存路径);
        $res['qrcode'] =  R(substr($dir,5));
        return $res;
    }
}